spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/employee
    password: ''
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update